#!/usr/bin/env bash
#Debugging ngnix port 80
#Bearing in mind that Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
## How I solved it: delete the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. You do that by creating a symbolic link. 
sudo ln -sf /etc/nginx/sites-available/default/etc/nginx/sites-enabled/default
sudo service nginx restart
